### PR TITLE
Initial Conversion to Swift 3

### PR DESCRIPTION
**Pull request by daveanderson**
Very basic conversion to Swift3. Still has room for improvements. Was not able to get all tests passing because there is no existing token that supports all the unit tests. Please provide a token and I'll be happy to get the tests passing.

### CODE REVIEW

**Comment by chrismetcalf** [comment]
Awesome work! 🍻  

I'll see if I can get those tests working and make sure everything is copacetic!

**Comment by rprisram** [comment]
Hi Chris/Dave, Can you please let me know when Swift 3 version upgrade can be used in my app? I believe its still under review. Pls let me know how I can go about  using it. Sorry am new to all these.

**Comment by daveanderson** [comment]
I'm using my branch in an app presently. You could probably do likewise.

**Comment by chrismetcalf** [comment]
Merged! Thanks @daveanderson and @rprisram

**Pull request merged**
